### PR TITLE
use levelup 0.19.0

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by juliangruber** [comment]
or switch to `^`?

**Comment by ralphtheninja** [comment]
Prob a good idea. That would install `0.20.x`, `0.21.x` .. right?

**Comment by juliangruber** [comment]
oh wait, we're on `0.x.x`, so no it won't. @rvagg should have an answer here

**Comment by Trott** [comment]
Any chance I can persuade someone to merge this as is? `~` and `^` behave identically for `0.x.y` where `x` > 0. So it shouldn't matter here which one is used. If there's a better solution, it can be another pull request. In the meantime, users get newer better moar awesomer levelup with the version bump in this PR.

**Comment by ralphtheninja** [comment]
I can merge it but @rvagg still has to release it :)

**Comment by ralphtheninja** [comment]
@rvagg We need a release of this when you have time please :)

**Pull request merged**
