### PR TITLE
null options should not be treated as object

### PR DESCRIPTION
**Pull request by deian**
Followup on #9

### CODE REVIEW

**Comment by juliangruber** [comment]
I'm +-0 on this, can you explain why you're interested in this change?

**Comment by deian** [comment]
I would like to be able to write a function 
```javascript
function mylevel(loc, opts, cb) {
...
require('level')(loc, opts, cb);
...
```

and not have to check if opts was passed in since you're already kind of doing that.

**Comment by ralphtheninja** [comment]
:+1: Accepting `null` as object is not correct.

**Comment by juliangruber** [comment]
cheers! released as v0.19.1

**Pull request merged**
